"""Subclass of GUI_mainFrame, which is generated by wxFormBuilder."""

import wx
import gui

# Implementing GUI_mainFrame
class MainFrame( gui.GUI_mainFrame ):
	def __init__( self, parent ):
		gui.GUI_mainFrame.__init__( self, parent )
	
	# Handlers for GUI_mainFrame events.
	def m_rtMainText( self, event ):
		self.m_statusBar.SetStatusText("Are you writing text??")
	
	def m_btHelloClick( self, event ):
		self.m_btPython.Enable(True)
		self.m_rtMain.AppendText("Hello")
	
	def m_btPythonClick( self, event ):
		self.m_rtMain.AppendText(" Python!")
	
	def m_mniOpenClick( self, event ):
		fdlg = wx.FileDialog(self,"Choose a file","Open file",wx.EmptyString,"*.*",wx.FD_OPEN | wx.FD_FILE_MUST_EXIST);
		if fdlg.ShowModal() != wx.ID_OK:
			return;
		self.m_rtMain.LoadFile(fdlg.GetPath())
			
	def m_mniSaveClick( self, event ):
		fdlg = wx.FileDialog(self,"Choose a file","Save file",wx.EmptyString,"*.*",wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT);
		if fdlg.ShowModal() != wx.ID_OK:
			return;
		self.m_rtMain.SaveFile(fdlg.GetPath())
			
	def m_mniExitClick( self, event ):
		self.Close()
	
	def m_mniAboutClick( self, event ):
		wx.MessageBox("oneminutepython template. ","oneminutepython")
	
	
